INSERT INTO Units (UnitName, StateId)
SELECT u.UnitName, s.StateId
	FROM (
		VALUES ('Lagos State', 'LASU'),
        ('Lagos State', 'UNILAG'),
        ('Lagos State', 'YABATECH'),
        ('Lagos State', 'LASUSTECH'),
        ('Oyo State', 'FCC Ibadan'),
        ('Oyo State', 'LAUTECH'),
        ('Oyo State', 'Lead City'),
        ('Oyo State', 'Moor'),
        ('Oyo State', 'OYSCATECH'),
        ('Oyo State', 'SPED'),
        ('Oyo State', 'TOPS'),
        ('Oyo State', 'TPI'),
        ('Oyo State', 'UI'),
        ('Ogun State', 'COE Osiele'),
        ('Ogun State', 'FPI'),
        ('Ogun State', 'FUNAAB'),
        ('Ogun State', 'MAPOLY'),
        ('Ogun State', 'OSPOHAS'),
        ('Ogun State', 'OOU'),
        ('Ogun State', 'TASUED'),
        ('Kwara State', 'Al-Hikmah'),
        ('Kwara State', 'FEDPOFFA'),
        ('Kwara State', 'Kwara Poly'),
        ('Kwara State', 'KWASU'),
        ('Kwara State', 'UNILORIN'),
        ('Ondo State', 'AAUA'),
        ('Ondo State', 'AFUED'),
        ('Ondo State', 'FUTA'),
        ('Ekiti State', 'EKSU'),
        ('Ekiti State', 'FEDPOLY Ado'),
        ('Ekiti State', 'FUOYE'),
        ('Osun State', 'Fountain'),
        ('Osun State', 'FEDPOLY Ede'),
        ('Osun State', 'Ila'),
        ('Osun State', 'OAU'),
        ('Osun State', 'Osun Poly'),
        ('Osun State', 'UNILESA'),
        ('Osun State', 'UNIOSUN'),
        ('Osun State', 'Westland/Crestfield'),
        ('Niger State', 'FUTMINNA'),
        ('Niger State', 'Lapai'),
        ('Individual Units', 'BUK'),
        ('Individual Units', 'UNIABUJA'),
        ('Individual Units', 'Kaduna'),
        ('Individual Units', 'Zaria'),
        ('Individual Units', 'UDUS'),
        ('Individual Units', 'FEDPOLY Nasarawa'),
        ('Individual Units', 'UNIBEN'),
        ('Individual Units', 'UNICAL')
	)
	AS u(StateName,UnitName)
    INNER JOIN States s ON u.StateName = s.StateName
