// <auto-generated />
using AmsaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AmsaAPI.Migrations
{
    [DbContext(typeof(AmsaDbContext))]
    [Migration("20250817184852_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AmsaAPI.Data.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DepartmentId")
                        .HasName("PK__Departme__B2079BEDCF4DB986");

                    b.HasIndex(new[] { "DepartmentName" }, "UQ__Departme__D949CC34646C8B5B")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("AmsaAPI.Data.Level", b =>
                {
                    b.Property<int>("LevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LevelId"));

                    b.Property<string>("LevelType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("NationalId")
                        .HasColumnType("int");

                    b.Property<int?>("StateId")
                        .HasColumnType("int");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("LevelId");

                    b.HasIndex("NationalId");

                    b.HasIndex("StateId");

                    b.HasIndex("UnitId");

                    b.HasIndex(new[] { "LevelType", "NationalId", "StateId", "UnitId" }, "UQ_Levels_LevelType_Id")
                        .IsUnique()
                        .HasFilter("[NationalId] IS NOT NULL AND [StateId] IS NOT NULL AND [UnitId] IS NOT NULL");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("AmsaAPI.Data.LevelDepartment", b =>
                {
                    b.Property<int>("LevelDepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LevelDepartmentId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.HasKey("LevelDepartmentId")
                        .HasName("PK__LevelDep__70EB3E688D7838FC");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("LevelId");

                    b.ToTable("LevelDepartments");
                });

            modelBuilder.Entity("AmsaAPI.Data.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Mkanid")
                        .HasColumnType("int")
                        .HasColumnName("MKANID");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("MemberId")
                        .HasName("PK__tmp_ms_x__0CF04B18844A1307");

                    b.HasIndex("UnitId");

                    b.HasIndex(new[] { "Phone" }, "UQ__tmp_ms_x__5C7E359E3AD99E1D")
                        .IsUnique()
                        .HasFilter("[Phone] IS NOT NULL");

                    b.HasIndex(new[] { "Mkanid" }, "UQ__tmp_ms_x__706BAAA967D044CC")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__tmp_ms_x__A9D10534C9D85A05")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("AmsaAPI.Data.MemberLevelDepartment", b =>
                {
                    b.Property<int>("MemberLevelDepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberLevelDepartmentId"));

                    b.Property<int>("LevelDepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.HasKey("MemberLevelDepartmentId")
                        .HasName("PK__MemberLe__C4CEBAB85CF42426");

                    b.HasIndex("LevelDepartmentId");

                    b.HasIndex("MemberId");

                    b.ToTable("MemberLevelDepartments");
                });

            modelBuilder.Entity("AmsaAPI.Data.National", b =>
                {
                    b.Property<int>("NationalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NationalId"));

                    b.Property<string>("NationalName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("NationalId")
                        .HasName("PK__National__E9AA32FB057063F4");

                    b.HasIndex(new[] { "NationalName" }, "UQ__National__1D8A5E87EDFF4DF5")
                        .IsUnique();

                    b.ToTable("National", (string)null);
                });

            modelBuilder.Entity("AmsaAPI.Data.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StateId"));

                    b.Property<int>("NationalId")
                        .HasColumnType("int");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StateId")
                        .HasName("PK__States__C3BA3B3A5778F3FA");

                    b.HasIndex("NationalId");

                    b.HasIndex(new[] { "StateName" }, "UQ__States__554763159073B91B")
                        .IsUnique();

                    b.ToTable("States");
                });

            modelBuilder.Entity("AmsaAPI.Data.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitId"));

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UnitId")
                        .HasName("PK__Units__44F5ECB508D31CE9");

                    b.HasIndex("StateId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("AmsaAPI.Data.Level", b =>
                {
                    b.HasOne("AmsaAPI.Data.National", "National")
                        .WithMany("Levels")
                        .HasForeignKey("NationalId")
                        .HasConstraintName("FK_Levels_National");

                    b.HasOne("AmsaAPI.Data.State", "State")
                        .WithMany("Levels")
                        .HasForeignKey("StateId")
                        .HasConstraintName("FK_Levels_States");

                    b.HasOne("AmsaAPI.Data.Unit", "Unit")
                        .WithMany("Levels")
                        .HasForeignKey("UnitId")
                        .HasConstraintName("FK_Levels_Units");

                    b.Navigation("National");

                    b.Navigation("State");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("AmsaAPI.Data.LevelDepartment", b =>
                {
                    b.HasOne("AmsaAPI.Data.Department", "Department")
                        .WithMany("LevelDepartments")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK__LevelDepa__Depar__6FE99F9F");

                    b.HasOne("AmsaAPI.Data.Level", "Level")
                        .WithMany("LevelDepartments")
                        .HasForeignKey("LevelId")
                        .IsRequired()
                        .HasConstraintName("FK_LevelDepartments_Levels");

                    b.Navigation("Department");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("AmsaAPI.Data.Member", b =>
                {
                    b.HasOne("AmsaAPI.Data.Unit", "Unit")
                        .WithMany("Members")
                        .HasForeignKey("UnitId")
                        .IsRequired()
                        .HasConstraintName("FK__Members__UnitId__0C85DE4D");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("AmsaAPI.Data.MemberLevelDepartment", b =>
                {
                    b.HasOne("AmsaAPI.Data.LevelDepartment", "LevelDepartment")
                        .WithMany("MemberLevelDepartments")
                        .HasForeignKey("LevelDepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK__MemberLev__Level__71D1E811");

                    b.HasOne("AmsaAPI.Data.Member", "Member")
                        .WithMany("MemberLevelDepartments")
                        .HasForeignKey("MemberId")
                        .IsRequired()
                        .HasConstraintName("FK__MemberLev__Membe__0B91BA14");

                    b.Navigation("LevelDepartment");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("AmsaAPI.Data.State", b =>
                {
                    b.HasOne("AmsaAPI.Data.National", "National")
                        .WithMany("States")
                        .HasForeignKey("NationalId")
                        .IsRequired()
                        .HasConstraintName("FK__States__National__60A75C0F");

                    b.Navigation("National");
                });

            modelBuilder.Entity("AmsaAPI.Data.Unit", b =>
                {
                    b.HasOne("AmsaAPI.Data.State", "State")
                        .WithMany("Units")
                        .HasForeignKey("StateId")
                        .IsRequired()
                        .HasConstraintName("FK__Units__StateId__619B8048");

                    b.Navigation("State");
                });

            modelBuilder.Entity("AmsaAPI.Data.Department", b =>
                {
                    b.Navigation("LevelDepartments");
                });

            modelBuilder.Entity("AmsaAPI.Data.Level", b =>
                {
                    b.Navigation("LevelDepartments");
                });

            modelBuilder.Entity("AmsaAPI.Data.LevelDepartment", b =>
                {
                    b.Navigation("MemberLevelDepartments");
                });

            modelBuilder.Entity("AmsaAPI.Data.Member", b =>
                {
                    b.Navigation("MemberLevelDepartments");
                });

            modelBuilder.Entity("AmsaAPI.Data.National", b =>
                {
                    b.Navigation("Levels");

                    b.Navigation("States");
                });

            modelBuilder.Entity("AmsaAPI.Data.State", b =>
                {
                    b.Navigation("Levels");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("AmsaAPI.Data.Unit", b =>
                {
                    b.Navigation("Levels");

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
